### ISSUE TITLE
Demo page error in Chrome

### ISSUE THREAD

**Issue by mishazawa** [Kagami/vmsg#1]
Hello. I have opened demo page, allow microphone usage and have this popup error:

```
Error: CompileError: AsyncCompile: Wasm decoding failed: 
expected magic word 00 61 73 6d, found 3c 21 44 4f @+0
```

Browser 

Chrome Version 64.0.3282.140 (Official Build) (64-bit)

OS 

Ubuntu 14.04

Console error:

![image](https://user-images.githubusercontent.com/7611372/36311466-0dad855c-1334-11e8-9e0e-f1f1b2a89660.png)

Maybe helpful...

**Comment by Kagami** [comment]
Fixed, thanks.
