### ISSUE TITLE
Error on Chrome 60.0.3112.101 (Official Build) (64-bit)  - Ubuntu

### ISSUE THREAD

**Issue by FDN73** [Kagami/vmsg#11]
I have tried it on Chrome 60.0.3112.101 (Official Build) (64-bit) and I get this: Error: TypeError: WebAssembly.compileStreaming(): Argument 0 must be provided and must be a Response or Response promise 

On Firefox 59.0.2 (64-bit) it works flawlessly.

**Comment by Kagami** [comment]
I can reproduce that.

Very strange issue, might be bug of Chrome 60. MDN [states](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiateStreaming#Browser_compatibility) that it's available only in Chrome 61+ yet `WebAssembly.instantiateStreaming` exists in Chrome 60 but doesn't work properly. `WebAssembly.instantiate` works.

Not sure how to fix that properly. Is there particular reason you use Chrome 60?

**Comment by FDN73** [comment]
Well, my ubuntu has not updated itself automatically to the newest chrome version... anyway I am just evaluating webassembly and check possible use cases, so for me it's not a priority to see this problem fixed.
In a (probably enough distant) future we may find it useful to port some audio processing libraries we have to the web platform, but nothing in the near term.
Thanks for your efforts!

**Comment by Kagami** [comment]
I've pushed fix anyway, just in case. Could you please try it?

Thanks for your bug report.

**Comment by FDN73** [comment]
Unfortunately I have not installed the development chain and right now I cannot do it, I've just tried the published demo - I see that the wasm file is still the old one so I would need to rebuild all...

**Comment by Kagami** [comment]
No, fix is on JS side and I've already pushed it to github pages. (Just make sure to Ctrl+Shift+R to get a fresh version.)

**Comment by FDN73** [comment]
Ok, tested it, now it works! Thanks.

**Comment by FDN73** [comment]
Works on Firefox too (tested just for completeness...)
