### ISSUE TITLE
NetworkError on Record in Firefox

### ISSUE THREAD

**Issue by skierpage** [Kagami/vmsg#12]
Both Firefox 62.0a1 Nightly on Windows 10 and Firefox 60.0.1 on Android, when I click [Record] I'm prompted to allow kagami.github.io to use my microphone, then both report Error: "TypeError: NetworkError when attempting to fetch resource." in a vmsg-popup . 

On desktop, the developer console has a long error stack
```
Error: "TypeError: NetworkError when attempting to fetch resource."  at 4fd14265bdd18cc7447ea3ab5f8313f6.js:50:8938 
λ onmessage    https://kagami.github.io/vmsg/4fd14265bdd18cc7447ea3ab5f8313f6.js:50:4692
λ value        https://kagami.github.io/vmsg/4fd14265bdd18cc7447ea3ab5f8313f6.js:50:4600
...
λ require      https://kagami.github.io/vmsg/4fd14265bdd18cc7447ea3ab5f8313f6.js:1:584
λ <anonymous>  https://kagami.github.io/vmsg/4fd14265bdd18cc7447ea3ab5f8313f6.js:1:9
```
Then "Error: no record made"

**Comment by Kagami** [comment]
Hi, sorry for delay. Can you still reproduce the issue?

vmsg works for me in Firefox on both desktop and mobile. Your setup may have some issue with downloading WebAssembly module but I don't know what might causing that. Maybe try with a clean profile?

**Comment by skierpage** [comment]
I just retried in Firefox 66.0a1 Nightly for Linux and whatever Firefox for Android is at, and had no problem. I can't test Firefox for Windows right now but let's assume the bug went away!

**Comment by Kagami** [comment]
Thanks for testing!
