### ISSUE TITLE
separate section in readme.md for the 3 demos and 1 usage

### ISSUE THREAD

**Issue by octavn** [Kagami/vmsg#13]
Hi,

I'm looking into `vmsg` for the WebAssembly library after researching both `Recorder.js` (wav only) and `Web Audio Recorder` (same LAME library but compiled to asm.js).

It would be quite easier to get up and running with `vmsg` if all 4 demos 

1. https://kagami.github.io/vmsg/
2. https://github.com/Kagami/vmsg/tree/master/demo
3. https://github.com/Kagami/vmsg#usage
4. https://codesandbox.io/s/v67oz43lm7

would be grouped together and documented together in a _demos_ section in readme.md

**Comment by Kagami** [comment]
First and second links are the same demo. And I think it's already grouped pretty clear in Usage section?
