### ISSUE TITLE
FR: support encoding to AAC-LC?

### ISSUE THREAD

**Issue by henrylearn2rock** [Kagami/vmsg#18]
AAC as well supported as mp3 in browers
https://en.wikipedia.org/wiki/HTML5_audio#Supported_audio_coding_formats

ffmpeg native aac encoder
https://trac.ffmpeg.org/wiki/Encode/AAC#NativeFFmpegAACEncoder

Licensing: 

> Licensee's products that are not end-user products (e.g. components or implementations) are not covered by the license and would require that the party incorporating such a component or implementation into its end-user product obtain a license.
> 
> License fees are due on the sale of encoders and/or decoders only. There are no patent license fees due for the distribution of bit-streams encoded in AAC, whether such bit-streams are broadcast, streamed over a network, or provided on physical media.
> 
> 

http://www.via-corp.com/us/en/licensing/aac/faq.html

What do you think?  AAC should compress even better than mp3 in lower bitrate, but I'm not sure about the encoder speed.  What bitrate does vmsg use? I thought you use CBR but looking at a few samples they range from 48kps to 56kps?

**Comment by Kagami** [comment]
You can't distribute AAC encoder in binary form per [wiki](https://en.wikipedia.org/wiki/Advanced_Audio_Coding#Licensing_and_patents). Also free implementations such as FFmpeg's are not as good as proprietary.

>What bitrate does vmsg use?

VBR -V5
