### ISSUE TITLE
Some issue with codesandbox example

### ISSUE THREAD

**Issue by koraysels** [Kagami/vmsg#21]
is there a way to lose the weird form that opens when you want to record? I'd like to implement my own interface. I just need to be able to record audio from a microphone is a smal file format, readable by ios.

**Comment by Kagami** [comment]
See [this demo](https://codesandbox.io/s/v67oz43lm7).

**Comment by koraysels** [comment]
Great! only the demo doesn/t seem to work.. (tested chrome on mac and mobile safari ios12)

**Comment by Kagami** [comment]
Ok, I will test it, thanks.

**Comment by Kagami** [comment]
Just downloaded .zip of that codesandbox, installed dependencies and started the dev server.
Everything seems to be working. What exactly doesn't work for you?

**Comment by koraysels** [comment]
I mean the online version of codesandbox..
Not when you download it. Perhaps i misunderstood
