### ISSUE TITLE
Demo broken on Firefox for Android

### ISSUE THREAD

**Issue by otbe** [Kagami/vmsg#22]
Hi there,

I just tried our demo in my mobile firefox (latest) on android 9 and I get 
```
NotAllowedError: The request is not allowed by the user agent or the platform in the current context.
```
There's also no mic permission request dialog.

Any idea whats wrong?

Thanks you 👍

**Comment by Kagami** [comment]
That's strange, because it works perfectly fine for me on Android 9 in latest Firefox.
Maybe try to allow use of microphone in app permissions for Firefox?

**Comment by Kagami** [comment]
Also, make sure you're opening demo from the https site, e.g. https://kagami.github.io/vmsg/

**Comment by otbe** [comment]
Sorry for my late response :)

Super strange. Firefox was not allowed to use my mic at all in the app permissions. I dont remember that I disabled it explicitly, but who knows. We tried it on two different phones (an older Samsung and my Xiaomi A1) and it was disabled on both phones. 

Anyway, thank you very much!
