### ISSUE TITLE
[ERROR] import in MeteorJS

### ISSUE THREAD

**Issue by binlux** [Kagami/vmsg#26]
when inporting es6 version we get an error untill we import es5 version like that
 import vmsg from 'vmsg/vmsg.es5'

**Comment by Kagami** [comment]
What error?

**Comment by binlux** [comment]
a lot of errors when importing vmsg.js but when importing vmsg.es5 it works fine
you can install meteor in try to import vmsg.js
![sans titre](https://user-images.githubusercontent.com/11628272/51431969-57463800-1c28-11e9-8642-a483e3749d97.png)

**Comment by binlux** [comment]
it does not affect new meteor versions, maybe it's related to meteor.
