### ISSUE TITLE
demo doesnt work in chrome - Promise did not implement oncancel

### ISSUE THREAD

**Issue by bukso** [Kagami/vmsg#27]
When I open the demo it doesnt work, I see only a error in the console:

https://codesandbox.io/s/v67oz43lm7

WARNING: Promise with no error callback:undefined raven.js:55 
Error: Promise did not implement oncancel

**Comment by Kagami** [comment]
Doesn't work for me on this site too. But works fine if I download the package and build by myself.
Might be sandboxing issue.
