### ISSUE TITLE
Cannot read property 'vmsg_flush' of null

### ISSUE THREAD

**Issue by bknill** [Kagami/vmsg#28]
Hi,

I get this error randomly.. often on short recordings.

```
Uncaught TypeError: Cannot read property 'vmsg_flush' of null
    at vmsg_flush (blob:https://localhost:3000/d90fc477-de7d-45da-a372-6707d7cb41bf:77)
    at onmessage (blob:https://localhost:3000/d90fc477-de7d-45da-a372-6707d7cb41bf:166)
vmsg_flush @ blob:https://localhost:3000/d90fc477-de7d-45da-a372-6707d7cb41bf:77
onmessage @ blob:https://localhost:3000/d90fc477-de7d-45da-a372-6707d7cb41bf:166
```

**Comment by Kagami** [comment]
Sounds like race condition between `init` and `stop` messages in a Worker. Are you waiting for the `initWorker()` Promise before starting the recording? Could you please show your code?

**Comment by bknill** [comment]
Thanks. This is from a Redux action.

```
import vmsg from 'vmsg'
const recorder = new vmsg.Recorder({
  wasmURL: "https://unpkg.com/vmsg@0.3.0/vmsg.wasm"
})

      startWebRecorder()

const startWebRecorder = async () => {
  await recorder.initAudio()
  await recorder.initWorker()
  recorder.startRecording()
}
```

Then on stop

`recorder.stopRecording().then(res => upload(res, type, id))`

**Comment by bknill** [comment]
I'm not waiting for the initWorker promise, how would i add that to the start function?

**Comment by Kagami** [comment]
Is it possible you're calling `stopRecording` before `startWebRecorder()` Promise fulfilled?

>I'm not waiting for the initWorker promise, how would i add that to the start function?

You may make yout buttons disabled by default and activate with e.g.

```js
startWebRecorder().then(() => {
  this.setState({recording: true});
});
```

and then use `disabled={!this.state.recording}` for your stop button.

You need to init worker only once btw, don't create a new one for every record. Probably API should disallow this...

**Comment by bknill** [comment]
thanks I've done a check to see if it's been initialised and it works better
