### ISSUE TITLE
Error: getUserMedia is not implemented in this browser

### ISSUE THREAD

**Issue by j1980mac** [Kagami/vmsg#32]
Awesome plugin! 

Works great on Desktop everywhere. However it appears that there's an issue with "getUserMedia" not being supported on mobile (iOS) Chrome and FireFox. 

Any possibility you'd be willing to fix that?

**Comment by Kolimar** [comment]
> The chrome app on your iPhone or iPad is not running "a full" version of chrome. It's capabilities are limited to the iOS platform. So getUserMedia and the like probably won't be available until Safari/Apple supports it.

Use safari instead of chrome/firefox in IOS.

**Comment by amcquade** [comment]
Error is thrown on chrome and firefox on windows.

**Comment by alirezabonab** [comment]
What happened to this issue? I m looking for answer too.
