### ISSUE TITLE
Encoding in wav format

### ISSUE THREAD

**Issue by cliff-ehla** [Kagami/vmsg#45]
Hi Kagami,

First of all, thanks for the package. It's hard to record on iOS, but it's possible with the library.

My projects employ a voice recognition API but that requires a .wav format audio data, which is not the default encoded format from vmsg.

I know the core of the encoding is in defined in the C layer, but I don't have any experience with C.
I found a relevant function `vmsg_encode` which sounds like the place to define the encoding, but I have no idea how could I modify on it.. Would appreciate your help if you add an audio encoding format for .wav apart from the default .mp3.

**Comment by Kagami** [comment]
Hi,

Have you tried https://github.com/mattdiamond/Recorderjs library? It does exactly that.
