### ISSUE TITLE
Tag new release?

### ISSUE THREAD

**Issue by adamfranco** [Kagami/vmsg#62]
Hi Kagami, would you mind tagging a new release? v0.3.6 is almost two years old at this point and it would be great if the recent dependency changes and accessibility fixes from #47 were available to be deployed easily through package-managers. 

As background, I've released a [Drupal audiorecorder module](https://www.drupal.org/project/audiorecorder) that utilizes vmsg and now that others have started using it too, the need to apply patches to vmsg makes the installation process more difficult than it needs to be. Thanks in advance!

**Comment by Kagami** [comment]
Thanks for heads up, just published 0.4.0.
