### ISSUE TITLE
embed vmsg.wasm directly

### ISSUE THREAD

**Issue by transitive-bullshit** [Kagami/vmsg#8]
It'd be great if `vmsg.wasm` was embedded directly via an ArrayBuffer or as a compile-time step.

Having the end user reference the URL of `vmsg.wasm` is pretty clunky, though I understand why it's setup that way at the moment.

**Comment by Kagami** [comment]
Unfortunately it won't be effecient. The whole point of WebAssembly is that it can be parsed fast. If you put it back into JavaScript file, you lose main benefits - compactness and small parsing time.

If you wish you can include `vmsg.wasm` with e.g. [arraybuffer-loader](https://github.com/pine/arraybuffer-loader):

```js
const buffer = require("arraybuffer!./vmsg.wasm");
const blob = new Blob([buffer], {type: "application/wasm"});
const wasmURL = URL.createObjectURL(blob);
```

that will work.

**Comment by transitive-bullshit** [comment]
I ended up doing something [similar](https://github.com/transitive-bullshit/react-mp3-recorder/blob/master/src/index.js) for react-mp3-recorder. This doesn't seem particularly efficient, however.

**Comment by Kagami** [comment]
I've just tried, seems like you can just pass data URI to fetch directly:

```js
> url = 'data:application/wasm;base64,' + btoa("123")
"data:application/wasm;base64,MTIz"
> fetch(url).then(res => res.arrayBuffer()).then(b => console.log(new Uint8Array(b)))
Uint8Array(3) [49, 50, 51]
```

**Comment by transitive-bullshit** [comment]
Good call -- just updated my impl.

**Comment by Kagami** [comment]
Can we close this now?
