### ISSUE TITLE
Publish new version with exported Recorder

### ISSUE THREAD

**Issue by Gregoor** [Kagami/vmsg#9]
Hi there, thanks for the great work!
I'm looking into using this for [Common Voice](https://github.com/mozilla/voice-web). Atm we're using MediaRecorder which (as you well know) doesn't let us support Safari & Edge. [I investigated using a lame encoder written in JS](https://github.com/mozilla/voice-web/pull/800) but that didn't seem to work for iOS. So my next thought was to go full WASM and fortunately I found that somebody already did the heavy lifting. Awesome! Also can confirm that it works with iOS 11.3 (discussion in #3 was very helpful) & Edge.
I was wondering if you could publish the most recent version to NPM, so that we can use the recently extracted Recorder?

**Comment by Kagami** [comment]
Published v0.3.0.

**Comment by Gregoor** [comment]
Wow! That was lightning-fast. Thank you! 🙂
